twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public': public_path
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        docs: '@App\Service\DocumentStorage'
        app_currency: '%env(string:APP_CURRENCY)%'
