version: '3.9'

services:
  web:
    build:
      context: ./.docker/web
    ports:
      - "80"
    volumes:
      - .:/var/www/app
    networks:
      - backend
      - proxy

  mongodb:
    image: mongo:5.0.4
    volumes:
      - mongodata:/data/db
    networks:
      - backend

volumes:
  mongodata:

networks:
  proxy:
    external:
      name: nginx-proxy
  backend:
